spring:
  mvc:
    path_match:
      matching-strategy: ant_path_matcher

  datasource:
    master:
      hikari:
        maxLifetime: 300000
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave:
      hikari:
        maxLifetime: 300000
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave2:
      hikari:
        maxLifetime: 300000
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
  jpa:
# local
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    RDS
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URI}

  rabbitmq:
    host: ${RMQ_HOST}
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}

  #multipart file 기본 설정 1MB
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

springdoc:
  swagger-ui:
    path: /api-doc.html

jwt:
  secret-key-source: ${SECRET_KEY_SOURCE}

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESSKEY}
      secretKey: ${SECRETKEY}
